pipeline:
  node:
    image: node:6.10.2-slim
    commands:
      - env
      - yarn
      - yarn test

  publish:
    image: plugins/docker
    username: josmo
    secrets: [ docker_password ]
    email: joachim.hill@gmail.com
    repo: classis/buzzerbutler
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: true
    when:
      local: false
      event: [ push ]

  deploy:
    image: peloton/drone-rancher
    url: http://rancher.seattleslow.com
    access_key: 845E1894659FB1248837
    secrets: [ rancher_secret_key ]
    service: butler/butler
    docker_image: classis/buzzerbutler:${DRONE_BUILD_NUMBER}
    start_first: false
    confirm: true
    timeout: 180
    when:
      local: false
      event: push
branches: [ master ]
